name: Release Package

on:
  release:
    types: [created]

jobs:
  # build:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 12
  #     - run: npm ci
  #     - run: npm test

  publish:
    # needs: build
    runs-on: ubuntu-latest

    continue-on-error: true

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 12
          always-auth: true
          check-latest: true
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: 12
      #     always-auth: true
      #     check-latest: true
      #     registry-url: "https://npm.pkg.github.com"
      #     scope: "@igorjs"
      # - run: npm install
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
